### ISSUE TITLE
Can't delete file

### ISSUE THREAD

**Issue by Abhi0725** [davidpiesse/nova-audio#3]
Once a file is uploaded we are not able to remove that.

**Comment by Abhi0725** [comment]
It seems 'deletebutton' component is not added.

![Screenshot 2019-04-17 at 11 17 00 AM](https://user-images.githubusercontent.com/8065382/56263937-7c045b80-6102-11e9-8598-6a185cec1fe2.png)

**Comment by davidpiesse** [comment]
Are you able to PR a fix for this issue?
