### ISSUE TITLE
Audio via external URL?

### ISSUE THREAD

**Issue by wwwroth** [davidpiesse/nova-audio#4]
If I want the audio sourced from an external url (HTTPS), how could I use this plugin? Is the availability there yet? If not, I can submit a PR probably. For example..

```php
class File extends Model
{
    ...
    public function getAudioURLAttribute()
    {
        return "https://" . config('azure.storage.shareName') .
                ".file.core.windows.net/allcontacts/" . $this->filename . 
                config('azure.storage.storageTokenString');
    }
}
```

```php
class File extends Resource
{
    public static $model = 'App\File';
    ....
    public function fields(Request $request)
    {
        return [
            ...
            Audio::make('Audio', 'audioURL'),
            ...
        ];
    }
}
```

```html
<audio controls="controls" preload="none" class="block w-full text-center" src="https://....file.core.windows.net/allcontacts/964...."></audio>
```

**Comment by davidpiesse** [comment]
I would recommend using Laravel's storage abilities to connect to your
Azure file store (in this case.).
That will give you a proper url to use for this linking.

D

**Comment by wwwroth** [comment]
Ah yes. Now that I've dug into the code, I think I'll be able to make this package work adding a new storage driver for Azure and not going through an attribute.
